-- ============================================================
-- CompluBeer · Modelo Medallion en Snowflake
-- Capa BRONZE · carga inicial de datos brutos
-- ============================================================

CREATE OR REPLACE DATABASE TALLER_DATO_DECISION;
CREATE OR REPLACE SCHEMA TALLER_DATO_DECISION.BRONZE;
CREATE OR REPLACE SCHEMA TALLER_DATO_DECISION.SILVER;
CREATE OR REPLACE SCHEMA TALLER_DATO_DECISION.GOLD;

USE DATABASE TALLER_DATO_DECISION;
USE SCHEMA BRONZE;

-- 1. File format para leer los CSV del caso
CREATE OR REPLACE FILE FORMAT FF_CSV_COMPLUBEER
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    ENCODING = 'UTF8';

-- 2. Stage interno para centralizar los ficheros del proyecto
CREATE OR REPLACE STAGE STG_COMPLUBEER
    FILE_FORMAT = FF_CSV_COMPLUBEER;

LIST @STG_COMPLUBEER;

-- 3. Tablas RAW: en Bronze preservamos el dato como llega.
-- Por eso se cargan los campos como STRING y se tiparán después en Silver.

CREATE OR REPLACE TABLE RAW_VENTAS (
    ID_VENTA STRING,
    FECHA_VENTA STRING,
    ANIO STRING,
    MES STRING,
    ID_PRODUCTO STRING,
    REGION STRING,
    CIUDAD STRING,
    CANAL STRING,
    VOLUMEN_HL STRING,
    INGRESOS_EUR STRING,
    DESCUENTO_EUR STRING,
    ORIGEN_FICHERO STRING
);

CREATE OR REPLACE TABLE RAW_PRODUCTOS (
    ID_PRODUCTO STRING,
    NOMBRE_PRODUCTO STRING,
    CATEGORIA STRING,
    ESTILO STRING,
    ABV STRING,
    IBU STRING,
    FORMATO STRING,
    FECHA_LANZAMIENTO STRING,
    ESTADO STRING,
    COSTE_UNITARIO_EUR STRING,
    PRECIO_LISTA_EUR STRING
);

CREATE OR REPLACE TABLE RAW_OBJETIVOS (
    ANIO STRING,
    MES STRING,
    REGION STRING,
    CANAL STRING,
    ID_PRODUCTO STRING,
    OBJETIVO_HL STRING,
    OBJETIVO_EUR STRING
);

CREATE OR REPLACE TABLE RAW_CANALES (
    CANAL_RAW STRING,
    CANAL_NORMALIZADO STRING
);

-- 4. Carga de ficheros CSV en tablas RAW
-- Antes de ejecutar estos COPY INTO, subir los CSV al stage STG_COMPLUBEER.

COPY INTO RAW_VENTAS
FROM @STG_COMPLUBEER/ventas_complubeer.csv
FILE_FORMAT = FF_CSV_COMPLUBEER;

COPY INTO RAW_PRODUCTOS
FROM @STG_COMPLUBEER/productos_complubeer.csv
FILE_FORMAT = FF_CSV_COMPLUBEER;

COPY INTO RAW_OBJETIVOS
FROM @STG_COMPLUBEER/objetivos_complubeer.csv
FILE_FORMAT = FF_CSV_COMPLUBEER;

COPY INTO RAW_CANALES
FROM @STG_COMPLUBEER/canales_complubeer.csv
FILE_FORMAT = FF_CSV_COMPLUBEER;

-- 5. Validación rápida de volumen cargado
SELECT 'RAW_VENTAS' AS tabla, COUNT(*) AS filas FROM RAW_VENTAS
UNION ALL
SELECT 'RAW_PRODUCTOS', COUNT(*) FROM RAW_PRODUCTOS
UNION ALL
SELECT 'RAW_OBJETIVOS', COUNT(*) FROM RAW_OBJETIVOS
UNION ALL
SELECT 'RAW_CANALES', COUNT(*) FROM RAW_CANALES;

-- Conteos esperados del caso:
-- RAW_VENTAS:     1066
-- RAW_PRODUCTOS:  10
-- RAW_OBJETIVOS:  638
-- RAW_CANALES:    8
